### ISSUE TITLE
Removal of unsubscribed tokens from the subscribed token Hashmap

### ISSUE THREAD

**Issue by SPRAGE** [kaychaks/kiteticker-async#8]
Once the tokens are unsubscribed they are not being removed from the "subscribed_tokens: HashMap<u32, Mode>" . I do not have the proper technical knowledge as to the format of how an issue must be put forth but I have found a solution. Below is the updated unsubscribe method implemented on the KiteTickerSubscriber struct.

```
pub async fn unsubscribe(
    &mut self,
    instrument_tokens: &[u32],
  ) -> Result<(), String> {
    let tokens = self.get_subscribed_or(instrument_tokens);
    match self.ticker.unsubscribe_cmd(tokens.as_slice()).await{
      Ok(_) => {
        self.subscribed_tokens.retain(|k, _| !tokens.contains(k));
        Ok(())
      },
      Err(e) => Err(e)
    }
  }
```

**Comment by kaychaks** [comment]
Thanks for the report 🙏. Would you mind providing the necessary pull request having both the code and the test case changes?
